[pytest]
# Fixed: Removed the double quotes around the URL string
base_url = https://opensource-demo.orangehrmlive.com/
pythonpath = .
addopts = -n auto --tracing=retain-on-failure --screenshot=only-on-failure --html=report.html --self-contained-html